AdministratorNei/nei-almoxarifado-api

- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/ItemEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RecordEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RoleEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/UserEntity.java
Criação das entidades Roles, Itens, Usuarios e Registros
> Criação das Entidades

- pom.xml
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RoleController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/RoleCreateDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/RoleResponseDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/RoleUpdateDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/RoleMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/repository/RoleRepository.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RoleService.java
Recursos Adicionados:
1. Criação de DTOs para padronizar as requisições e respostas
2. Adicionado dependência para a conversão dos DTOs
3. Criado a funcionalidade de Conversão de DTOs para a Entidade e vice versa
4.  Criação da funcionalidades
- Criar Roles
- Buscar roles pelo ID
- Buscar todas as roles existentes
- Mudar o nome de uma role
- Deletar uma role pelo ID
> Criaçao da lógica para o gerenciamento das Roles

- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RoleEntity.java
- src/main/resources/db/migration/V2__Setup.sql
Resolução do problema da issue [#4](https://github.com/AdministratorNei/nei-almoxarifado-api/issues/4)
-  Adicionando a validação `NOT NULL` a coluna `id_role` da tabela `Usuarios`
-  Adicionando a validação `UNIQUE` a coluna `encargo` da tabela `Roles`
- Mudando o campo `unique` da anotação `@Column` da coluna `encargo` para `true`
> Build: Adicionando validações UNIQUE e NOT NULL a migration

- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/RoleResponseDto.java
Mudando tipo do atributo ID para Long na classe RoleResponseDto
> rodrigo/fix: id type error

- src/test/java/com/ufrn/nei/almoxarifadoapi/controller/RoleControllerTest.java
- src/test/java/com/ufrn/nei/almoxarifadoapi/service/RoleServiceTest.java
- src/test/resources/application-test.properties
- Configuração do banco de dados H2
- Foi utilizado Mockito para a criação dos testes
- Criação de testes para todos os métodos do roleSerivce, exceto para o método de exclusão
- Criação de testes para todos os métodos do roleController, exceto para o método de exclusão
> Rodrigo/test: Criação de testes para o Service da entidade Role

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RoleController.java
Mudança no código de resposta dos métodos `findRoleById()` e `findAllRoles()` de `FOUND` para `OK`
> Rodrigo/fix: Mudando código das respostas de FOUND para OK - Closes #10

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RoleController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemCreateDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemDetailsDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemUpdateDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/RoleMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/role/RoleCreateDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/role/RoleResponseDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/role/RoleUpdateDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/ItemEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RecordEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RoleEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/UserEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RoleService.java
- src/test/java/com/ufrn/nei/almoxarifadoapi/controller/RoleControllerTest.java
- src/test/java/com/ufrn/nei/almoxarifadoapi/service/RoleServiceTest.java
Criação de métodos auxiliares e construtores para Entidades e DTOs para facilitar no desenvolvimento e também refatoração de código nos `testes` para instanciar objetos utilizando construtores. E criação do pacote `role` dentro do pacote `dto`.
**Especifique**:  Refatoração de código.
NA
NA
> Rodrigo/refactor: Criação de métodos e construtores para Entidades e DTOs

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemUpdateDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/ItemMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/exception/CreateEntityException.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/exception/EntityNotFoundException.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestErrorMessage.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
- src/test/java/com/ufrn/nei/almoxarifadoapi/service/ItemServiceTest.java
Descrição da alteração que está sendo proposta.
**Especifique**: Tratamento de exceção 
Issue #9 
Criação da estrutura para lidar com exceções, criação de exceções personalizadas para a entidade Item e refatoração do teste de deletar usuário que não existe para conseguir interagir com a exceção lançada pelo método
> Rodrigo/feat: Criação das Classes Para o Tratamento de Exceção - Closes #9

- pom.xml
- src/main/java/com/ufrn/nei/almoxarifadoapi/config/SpringDocsOpenApiConfig.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/resources/application.properties
Descrição da alteração que está sendo proposta.
NA
Criação da documentação dos endpoints do controller Item utilizando o OpenApi e Swagger
> Rodrigo/docs: Criação da documentação dos endpoints do controller Item

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/exception/ItemNotActiveException.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
Descrição da alteração que está sendo proposta.
**Especifique**: Refatoração e criação de exceção personalizada.
NA
Refatoração para remover códigos redundantes e Criação de exceção personalizada caso o usuário remova um item que já foi excluido anteriormente.
> Rodrig/refactor: Refatoração do código do método delete e Adicionar lançamento de erro

- pom.xml
- src/main/java/com/ufrn/nei/almoxarifadoapi/config/SpringSecurityConfig.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/config/SpringTimeZoneConfig.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/AuthenticationController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/OperationController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RecordController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RoleController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/UserController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/UserMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/record/RecordCreateDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/user/UserLoginDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestErrorMessage.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/jwt/JwtAuthorizationFilter.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/jwt/JwtToken.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/jwt/JwtUserDetails.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/jwt/JwtUserDetailsService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/jwt/JwtUtils.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
- src/main/resources/db/migration/V7__CreateDefaultRoles.sql
Implementação do spring security para gerenciamento de acesso dos usuários pelas roles utilizando token JWT.
**Especifique**: NA
NA
NA
> Rodrigo/feat: Implementação do Spring Security

- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/RecordMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/RoleMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/UserMapper.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/ItemEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
Configurar a conversão do ModelMapper para evitar erros.
**Especifique**: NA
Refatoração do Mapper para usuário, record e role.
> Rodrigo/refactor: Refatorar funcionamento do ModelMapper

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/AuthenticationController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/OperationController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RecordController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RequestController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RoleController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/UserController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RequestService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RoleService.java
Documentar os endpoints da API.
NA
> Rodrigo/docs: Documentar os métodos

- src/main/java/com/ufrn/nei/almoxarifadoapi/config/SpringSecurityConfig.java
Consertar configuração do CORS
NA
> Rodrigo/fix: Consertar configuração do CORS

- src/main/java/com/ufrn/nei/almoxarifadoapi/repository/projection/UserProjection.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
Consertar erro ao criar usuário e adicionar campo 'existRecord' ao listar todos os usuários.
NA
> Rodrigo/fix: Consertar erro ao criar usuário 

- pom.xml
Lançar versão 1.0.0 da API
**Especifique**: Lançar uma release
NA
> Lançar versão 1.0.0

- pom.xml
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailTemplates.java
- src/main/resources/application.properties
Recursos adicionados Timeout ao envio do e-mail, campo Data ao cabeçalho dos e-mails, remoção do método Join() dos campos assíncronos, foi adicionado novos logs e resolução de outro bug ao enviar dois e-mails ao mesmo tempo.
As propriedades do Timeout foram adicionadas para envitar o congestionamento da Thread caso ocorresse a demora do envio, se o tempo de espera for maior que o Timeout definido o programa irá retornar uma excessão explicando qual foi a situação que gerou o timeout. Foram adicionados Timeout para três situações:
- Tempo máximo para estabelecer conexão entre o cliente e o servidor de e-mail
- Tempo máximo qeu o cliente de e-mail espera receber uma resposta do servidor
- Tempo máximo que o cliente de …
> Fix: Resolver problema ao enviar email

- pom.xml
- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RequestController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/repository/RequestRepository.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RequestService.java
Mudanças para o usuário conseguir obter as suas solicitações pelo status, id do item e todas as suas solicitações criadas
NA
> Feat: Usuário conseguir ver suas próprias solicitações

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemCreateDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemUpdateIdealAmountDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/ItemEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailTemplates.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/repository/UserRepository.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
- src/main/resources/db/migration/V15__StockLimitLevels.sql
Notificar administração pelo e-mail caso um ideal esteja abaixo da quantidade ideal.
NA
> Feat: Adicionar limite no estoque

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/UserController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
Mudar o PathVariable do endpoint `PUT api/v1/users/updateForgotPassword` de id para email.
**Especifique**: Refatoração de método 
NA
> Refactor: Mudar de id para e-mail para trocar senha esquecida

- pom.xml
Lançar versão 1.1.0 da API
**Especifique**: Lançamento de nova versão 
NA
> Lançar versão 1.1.0

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RequestController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/request/RequestAdminCommentDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/request/RequestResponseDTO.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RequestEntity.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/infra/mail/MailTemplates.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/repository/projection/RequestProjection.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RequestService.java
- src/main/resources/db/migration/V16__AddColumnAdminComment.sql
Adicionar comentário da administração as solicitações
Essa funcionalidade serve para a administração adicionar um comentário sobre alguma solicitação, Ex: Explicar pq recusou o pedido de algum item
> Feat: Adicionar comentário da administração as solicitações

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/OperationController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/OperationService.java
Refatorar método de deletar item
**Especifique**: Refatoração 
NA
> Refactor: Deletar Item 

- src/main/java/com/ufrn/nei/almoxarifadoapi/controller/UserController.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/dto/role/RoleUpdateDto.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/RoleService.java
- src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
Criar método para o ADMIN conseguir trocar a role dos usuários do sistema
NA
> Feat: Gerenciar usuário

- pom.xml
> Lançar versão 1.2.0
